<div style="text-align: right">Self Learning, Numpy</div>
<div style="text-align: right">Zixiao Wang, 24 October 2019, with material from <a href="https://www.tuicool.com/articles/r2yyei">Numpy Tutorial </a></div>

# Numpy Self Learning Linear algebra

[Document](https://docs.scipy.org/doc/numpy/reference/routines.html)

In [1]:
import numpy as np

In [4]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [5]:
a.T

array([[1, 3],
       [2, 4]])

In [10]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [17]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [18]:
np.dot(u,a)

array([[1., 2.],
       [3., 4.]])

In [22]:
np.trace(a)

5

In [21]:
help(np.trace)

Help on function trace in module numpy:

trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
    Return the sum along diagonals of the array.
    
    If `a` is 2-D, the sum along its diagonal with the given offset
    is returned, i.e., the sum of elements ``a[i,i+offset]`` for all i.
    
    If `a` has more than two dimensions, then the axes specified by axis1 and
    axis2 are used to determine the 2-D sub-arrays whose traces are returned.
    The shape of the resulting array is the same as that of `a` with `axis1`
    and `axis2` removed.
    
    Parameters
    ----------
    a : array_like
        Input array, from which the diagonals are taken.
    offset : int, optional
        Offset of the diagonal from the main diagonal. Can be both positive
        and negative. Defaults to 0.
    axis1, axis2 : int, optional
        Axes to be used as the first and second axis of the 2-D sub-arrays
        from which the diagonals should be taken. Defaults are the first two
       

In [20]:
np.trace(np.eye(10))

10.0