<div style="text-align:right;">Python Numpy</div>
<div style="text-align:right;">Brickea with Material from Mofan Python</div>

# Numpy

In [1]:
import numpy as np

## Attributes

* shape
* ndim
* size

In [3]:
a = np.array([[1,2,3],
             [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.shape

(2, 3)

In [6]:
a.ndim

2

In [7]:
a.size

6

## Creation

* array：创建数组
* dtype：指定数据类型
* zeros：创建数据全为0
* ones：创建数据全为1
* empty：创建数据接近0
* arrange：按指定范围创建数据
* linspace：创建线段

In [9]:
a = np.array([1,2],dtype = np.int)
a = np.array([1,2],dtype = np.float)
a = np.array([1,2],dtype = np.int32)
a = np.array([1,2],dtype = np.float32)

In [27]:
a = np.zeros((2,3))
print(a)
a = np.ones((2,3),dtype = np.int)
print(a)
a = np.empty((2,3),dtype = np.float32)
print(a)
a = np.arange(12).reshape((3,4))
print(a)
a = np.linspace(1,10,20)
print(a)
a = np.linspace(1,10,12).reshape((3,4))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[1.e-45 0.e+00 1.e-45]
 [0.e+00 0.e+00 0.e+00]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[[ 1.          1.81818182  2.63636364  3.45454545]
 [ 4.27272727  5.09090909  5.90909091  6.72727273]
 [ 7.54545455  8.36363636  9.18181818 10.        ]]


## 运算

* dot
* sum\min\max

In [28]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))

print(a)
# array([[1, 1],
#       [0, 1]])

print(b)
# array([[0, 1],
#       [2, 3]])

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [29]:
np.dot(a,b)

array([[2, 4],
       [2, 3]])

如果你需要对行或者列进行查找运算，就需要在上述代码中为 axis 进行赋值。 当axis的值为0的时候，将会以列作为查找单元， 当axis的值为1的时候，将会以行作为查找单元。

In [31]:
print("a =",a)

print("sum =",np.sum(a,axis=1))

print("min =",np.min(a,axis=0))

print("max =",np.max(a,axis=1))

a = [[1 1]
 [0 1]]
sum = [2 1]
min = [0 1]
max = [1 1]


* argmin() 
* argmax()
* mean()
* average()
* median()
* cumsum()
* diff()
* nonzero()

In [32]:
A = np.arange(2,14).reshape((3,4)) 

# array([[ 2, 3, 4, 5]
#        [ 6, 7, 8, 9]
#        [10,11,12,13]])
         
print(np.argmin(A))    # 0
print(np.argmax(A))    # 11

0
11


In [33]:
print(np.mean(A))        # 7.5
print(np.average(A))     # 7.5

7.5
7.5


In [37]:
print(np.median(A))       # 7.5

7.5


在cumsum()函数中：生成的每一项矩阵元素均是从原矩阵首项累加到对应项的元素之和。比如元素9，在cumsum()生成的矩阵中序号为3，即原矩阵中2，3，4三个元素的和。

In [38]:
print(np.cumsum(A)) 

[ 2  5  9 14 20 27 35 44 54 65 77 90]


diff函数计算的便是每一行中后一项与前一项之差。故一个3行4列矩阵通过函数计算得到的矩阵便是3行3列的矩阵。

In [39]:
print(np.diff(A))    

# [[1 1 1]
#  [1 1 1]
#  [1 1 1]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]


nonzero 这个函数将所有非零元素的行与列坐标分割开，重构成两个分别关于行和列的矩阵。

In [40]:
print(np.nonzero(A))    

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


* sort()
* transpose()
* clip()

In [44]:
np.sort(A)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [45]:
A.T

array([[ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12],
       [ 5,  9, 13]])

这个函数的格式是clip(Array,Array_min,Array_max)，顾名思义，Array指的是将要被执行用的矩阵，而后面的最小值最大值则用于让函数判断矩阵中元素是否有比最小值小的或者比最大值大的元素，并将这些指定的元素转换为最小值或者最大值。

In [46]:
np.clip(A,5,9)

array([[5, 5, 5, 5],
       [6, 7, 8, 9],
       [9, 9, 9, 9]])

## Flat

这一脚本中的flatten是一个展开性质的函数，将多维的矩阵进行展开成1行的数列。而flat是一个迭代器，本身是一个object属性。

In [49]:
print(A.flatten())

for item in A.flat:
    print(item)

[ 2  3  4  5  6  7  8  9 10 11 12 13]
2
3
4
5
6
7
8
9
10
11
12
13


## Array 合并

In [56]:
A = np.array([1,1,1])
B = np.array([2,2,2])
         
print(np.vstack((A,B)))    # vertical stack

[[1 1 1]
 [2 2 2]]


In [57]:
C = np.vstack((A,B))      
print(A.shape,C.shape)

(3,) (2, 3)


In [58]:
D = np.hstack((A,B))       # horizontal stack

print(D)
# [1,1,1,2,2,2]

print(A.shape,D.shape)
# (3,) (6,)

[1 1 1 2 2 2]
(3,) (6,)


说完了array的合并，我们稍稍提及一下前一节中转置操作，如果面对如同前文所述的A序列， 转置操作便很有可能无法对其进行转置（因为A并不是矩阵的属性），此时就需要我们借助其他的函数操作进行转置：

In [59]:
print(A[np.newaxis,:])
# [[1 1 1]]

print(A[np.newaxis,:].shape)
# (1,3)

print(A[:,np.newaxis])
"""
[[1]
[1]
[1]]
"""

print(A[:,np.newaxis].shape)
# (3,1)

[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
(3, 1)


当你的合并操作需要针对多个矩阵或序列时，借助concatenate函数可能会让你使用起来比前述的函数更加方便：

In [68]:
C = np.concatenate((A,B,B,A),axis=0)

print(C)
"""
array([[1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1]])
"""

D = np.concatenate((A[:,np.newaxis],B[:,np.newaxis],B[:,np.newaxis],A[:,np.newaxis]),axis=1)

print(D)
"""
array([[1, 2, 2, 1],
       [1, 2, 2, 1],
       [1, 2, 2, 1]])
"""

[1 1 1 2 2 2 2 2 2 1 1 1]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


'\narray([[1, 2, 2, 1],\n       [1, 2, 2, 1],\n       [1, 2, 2, 1]])\n'

## 分割

In [69]:
A = np.arange(12).reshape((3, 4))
print(A)
"""
array([[ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11]])
"""

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


'\narray([[ 0,  1,  2,  3],\n    [ 4,  5,  6,  7],\n    [ 8,  9, 10, 11]])\n'

### 纵向分割

In [74]:
np.split(A,2,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

### 横向分割

In [76]:
np.split(A, 3, axis=0)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

### 错误的分割

In [77]:
np.split(A, 3, axis=1)

ValueError: array split does not result in an equal division

范例的Array只有4列，只能等量对分，因此输入以上程序代码后Python就会报错。

### 不等量的分割

In [78]:
np.array_split(A, 3, axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]

In [79]:
np.vsplit(A, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [80]:
np.hsplit(A, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

## Copy in Numpy

In [82]:
a = np.array([11, 22, 33,  3])
b = a.copy()    # deep copy
print(b)        # array([11, 22, 33,  3])
a[3] = 44
print(a)        # array([11, 22, 33, 44])
print(b)        # array([11, 22, 33,  3])

[11 22 33  3]
[11 22 33 44]
[11 22 33  3]
